### ISSUE TITLE
Scheduled linkchecker

### ISSUE THREAD

**Issue by snim2** [softwaresaved/website#24]
It would be nice to add a [scheduled action](https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule) to run a linkchecker over the site. In GitLab I use something like this:

```yaml
test:
    stage: test
    image: ubuntu:18.04
    dependencies:
        - build
    except:
        - master
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq webfs linkchecker npm python-pip openjdk-8-jre
        - npm install -g bootlint
        - pip install html5validator
    script:
        - html5validator --root _site/
        - bootlint _site/*.html  # Assumes mark-up is HTML5 compliant.
        - cd _site && webfsd -p 4000
        - linkchecker http://localhost:4000/
    artifacts:
        paths:
            - _site
```

(this isn't necessarily the best way to do this in GitLab BTW!). 

For this site it might make more sense to run the tool over the live site, whereas the config above is intended to run over feature branches of a site that can be built and run locally.
